package com.invenio.mulepoc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-13T17:22:30.770+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "EaiParamWsService", 
                  wsdlLocation = "http://172.25.172.200:8080/EaiParamWsService/EaiParamWs?wsdl",
                  targetNamespace = "http://ws.global.mapping.eai.umgi.com/") 
public class EaiParamWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.global.mapping.eai.umgi.com/", "EaiParamWsService");
    public final static QName EaiParamWsPort = new QName("http://ws.global.mapping.eai.umgi.com/", "EaiParamWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://172.25.172.200:8080/EaiParamWsService/EaiParamWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EaiParamWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://172.25.172.200:8080/EaiParamWsService/EaiParamWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EaiParamWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EaiParamWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EaiParamWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns EaiParamWs
     */
    @WebEndpoint(name = "EaiParamWsPort")
    public EaiParamWs getEaiParamWsPort() {
        return super.getPort(EaiParamWsPort, EaiParamWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EaiParamWs
     */
    @WebEndpoint(name = "EaiParamWsPort")
    public EaiParamWs getEaiParamWsPort(WebServiceFeature... features) {
        return super.getPort(EaiParamWsPort, EaiParamWs.class, features);
    }

}
