package com.invenio.mulepoc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-13T17:22:30.759+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.global.mapping.eai.umgi.com/", name = "EaiParamWs")
@XmlSeeAlso({ObjectFactory.class})
public interface EaiParamWs {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2Key3Key4", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3Key4")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2Key3Key4Response", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3Key4Response")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2Key3Key4(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2,
        @WebParam(name = "Key3", targetNamespace = "")
        java.lang.String key3,
        @WebParam(name = "Key4", targetNamespace = "")
        java.lang.String key4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2ValidFrom", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2ValidFrom")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2ValidFromResponse", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2ValidFromResponse")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2ValidFrom(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2,
        @WebParam(name = "ValidFrom", targetNamespace = "")
        java.lang.String validFrom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2Key3", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2Key3Response", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3Response")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2Key3(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2,
        @WebParam(name = "Key3", targetNamespace = "")
        java.lang.String key3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2Key3Key4ValidFrom", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3Key4ValidFrom")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2Key3Key4ValidFromResponse", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3Key4ValidFromResponse")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2Key3Key4ValidFrom(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2,
        @WebParam(name = "Key3", targetNamespace = "")
        java.lang.String key3,
        @WebParam(name = "Key4", targetNamespace = "")
        java.lang.String key4,
        @WebParam(name = "ValidFrom", targetNamespace = "")
        java.lang.String validFrom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2Key3ValidFrom", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3ValidFrom")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2Key3ValidFromResponse", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Key3ValidFromResponse")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2Key3ValidFrom(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2,
        @WebParam(name = "Key3", targetNamespace = "")
        java.lang.String key3,
        @WebParam(name = "ValidFrom", targetNamespace = "")
        java.lang.String validFrom
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParamByKey1Key2", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamByKey1Key2Response", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamByKey1Key2Response")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParamByKey1Key2(
        @WebParam(name = "Key1", targetNamespace = "")
        java.lang.String key1,
        @WebParam(name = "Key2", targetNamespace = "")
        java.lang.String key2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findEaiParamValues", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindEaiParamValues")
    @WebMethod
    @ResponseWrapper(localName = "findEaiParamValuesResponse", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindEaiParamValuesResponse")
    public java.util.List<com.invenio.mulepoc.EaiParam> findEaiParamValues(
        @WebParam(name = "input", targetNamespace = "")
        com.invenio.mulepoc.ParamInput input
    ) throws Throwable_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAllEaiParam", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParam")
    @WebMethod
    @ResponseWrapper(localName = "findAllEaiParamResponse", targetNamespace = "http://ws.global.mapping.eai.umgi.com/", className = "com.invenio.mulepoc.FindAllEaiParamResponse")
    public java.util.List<com.invenio.mulepoc.EaiParam> findAllEaiParam();
}
