
package com.invenio.mulepoc;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-13T17:22:30.749+05:30
 * Generated source version: 2.5.1
 */

@SuppressWarnings("serial")
@WebFault(name = "Throwable", targetNamespace = "http://ws.global.mapping.eai.umgi.com/")
public class Throwable_Exception extends Exception {
    
    private com.invenio.mulepoc.Throwable throwable;

    public Throwable_Exception() {
        super();
    }
    
    public Throwable_Exception(String message) {
        super(message);
    }
    
    public Throwable_Exception(String message, com.invenio.mulepoc.Throwable throwable) {
        super(message);
        this.throwable = throwable;
    }

    public Throwable_Exception(String message, com.invenio.mulepoc.Throwable throwable, Throwable cause) {
        super(message);
        this.throwable = throwable;
    }

    public com.invenio.mulepoc.Throwable getFaultInfo() {
        return this.throwable;
    }
}
