#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/320170d7-2a11-4211-9c32-37cbcbffb35a
title: Test API
version: 1.0

/users.json:
  post:
    body: 
      application/json:      
    responses: 
      200:
        body: 
          application/json:
/users.xml:
  post:
    body: 
      application/xml:
    responses: 
      200:
        body: 
          application/xml:
            
            